import 'package:flutter/material.dart';
import 'package:flutter_login_system/page/2page.dart';
import 'package:flutter_login_system/page/Home.dart';
import 'package:flutter_login_system/page/New&Event.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp4 extends StatelessWidget {
  const FigmaToCodeApp4({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ContactMovieProject(),
        ]),
      ),
    );
  }
}

class ContactMovieProject extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1512,
          height: 1552,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFE4E4E4)),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 1512,
                height: 103,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 1512,
                        height: 103,
                        decoration: BoxDecoration(color: Colors.white),
                      ),
                    ),
                    Positioned(
                      left: 101,
                      top: 0,
                      child: Container(
                        width: 195,
                        height: 110,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage(
                                "pic/image/MOVIE_MINE2 1.jpg"), // ระบุ path ที่ถูกต้อง
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 641,
                      top: 39,
                      child: TextButton(
                        child: Text(
                          'Home',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 20,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        onPressed: () {
                          Navigator.pushReplacement(context,
                              MaterialPageRoute(builder: (context) {
                            //เปลี่ยนเป็นเว็บด้านใน
                            return FigmaToCodeApp1();
                          }));
                        },
                      ),
                    ),
                    Positioned(
                      left: 759,
                      top: 39,
                      child: TextButton(
                        child: Text(
                          'Discovery',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 20,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        onPressed: () {
                          Navigator.push(context,
                              MaterialPageRoute(builder: (context) {
                            //เปลี่ยนเป็นเว็บด้านใน
                            return MyHomePage2();
                          }));
                        },
                      ),
                    ),
                    Positioned(
                      left: 1118,
                      top: 39,
                      child: TextButton(
                        child: Text(
                          'Contaxt',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 20,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        onPressed: () {
                          Navigator.pushReplacement(context,
                              MaterialPageRoute(builder: (context) {
                            //เปลี่ยนเป็นเว็บด้านใน
                            return FigmaToCodeApp4();
                          }));
                        },
                      ),
                    ),
                    Positioned(
                      left: 915,
                      top: 39,
                      child: TextButton(
                        child: Text(
                          'New&Events',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 20,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        onPressed: () {
                          Navigator.pushReplacement(context,
                              MaterialPageRoute(builder: (context) {
                            //เปลี่ยนเป็นเว็บด้านใน
                            return FigmaToCodeApp3();
                          }));
                        },
                      ),
                    ),
                    Positioned(
                      left: 1239,
                      top: 32,
                      child: Container(
                        width: 239,
                        height: 39,
                        decoration: ShapeDecoration(
                          color: Color(0xFFF5F5F7),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(50),
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 200,
                      top: 228,
                      child: Container(
                        width: 119,
                        height: 119,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage(
                                "pic/image/phone-removebg-preview.png"), // ระบุ path ที่ถูกต้อง
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 1342,
                      top: 41,
                      child: Text(
                        'Search',
                        style: TextStyle(
                          color: Color(0xFF1D1D1F),
                          fontSize: 17,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w400,
                          height: 0,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                width: 2046,
                height: 1298,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 2046,
                        height: 518,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: AssetImage(
                                "pic/image/6_bruihfUTue21017 1.png"), // ระบุ path ที่ถูกต้อง
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 71,
                      top: 411,
                      child: Container(
                        width: 1369,
                        height: 887,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 1369,
                                height: 887,
                                decoration: ShapeDecoration(
                                  color: Colors.white,
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.only(
                                      topLeft: Radius.circular(60),
                                      topRight: Radius.circular(60),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 187,
                              top: 228,
                              child: Container(
                                width: 119,
                                height: 119,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: AssetImage(
                                        "pic/image/phone-removebg-preview.png"), // ระบุ path ที่ถูกต้อง
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 606,
                              top: 228,
                              child: Container(
                                width: 157,
                                height: 157,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: AssetImage(
                                        "pic/image/mail-removebg-preview.png"), // ระบุ path ที่ถูกต้อง
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 956,
                              top: 94,
                              child: Transform(
                                transform: Matrix4.identity()
                                  ..translate(0.0, 0.0)
                                  ..rotateZ(1.57),
                                child: Container(
                                  width: 502.02,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: Color(0xFF666666),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 434,
                              top: 94,
                              child: Transform(
                                transform: Matrix4.identity()
                                  ..translate(0.0, 0.0)
                                  ..rotateZ(1.57),
                                child: Container(
                                  width: 502.02,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: Color(0xFF666666),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 632,
                              top: 419,
                              child: Text(
                                'Email',
                                style: TextStyle(
                                  color: Color(0xFF666666),
                                  fontSize: 40,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 1114,
                              top: 419,
                              child: Text(
                                'Line',
                                style: TextStyle(
                                  color: Color(0xFF666666),
                                  fontSize: 40,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 515,
                              top: 485,
                              child: Text(
                                'SWUXXXX@g.swu.ac.th',
                                style: TextStyle(
                                  color: Color(0xFF666666),
                                  fontSize: 30,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 124,
                              top: 485,
                              child: Text(
                                '095-XXX-XXXX',
                                style: TextStyle(
                                  color: Color(0xFF666666),
                                  fontSize: 30,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 193,
                              top: 419,
                              child: Text(
                                'Call',
                                style: TextStyle(
                                  color: Color(0xFF666666),
                                  fontSize: 40,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 1071,
                              top: 474,
                              child: Text(
                                'Scan here',
                                style: TextStyle(
                                  color: Color(0xFF666666),
                                  fontSize: 30,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 1079,
                              top: 232,
                              child: Container(
                                width: 150,
                                height: 150,
                                decoration: BoxDecoration(
                                  image: DecorationImage(
                                    image: AssetImage(
                                        "pic/image/qr-removebg-preview.png"), // ระบุ path ที่ถูกต้อง
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 483,
                              top: 725,
                              child: Text(
                                'source by : IMDB and ROTTEN-TOMATOES',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 20,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 687,
                      top: 74,
                      child: Text(
                        'Contact Us',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 25,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w700,
                          height: 0,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                width: 1512,
                height: 151,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 1512,
                        height: 151,
                        decoration: BoxDecoration(color: Color(0xFF1D1D1F)),
                      ),
                    ),
                    Positioned(
                      left: 525,
                      top: 64,
                      child: Text(
                        'Copyright © 2023 Your Title. All rights reserved.',
                        style: TextStyle(
                          color: Color(0xFFD9D9D9),
                          fontSize: 20,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 0,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
