import 'package:flutter/material.dart';
import 'package:flutter_login_system/page/2page.dart';
import 'package:flutter_login_system/page/Home.dart';
import 'package:flutter_login_system/page/contaxt.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp3 extends StatelessWidget {
  const FigmaToCodeApp3({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          NewsEventMovieProjrct(),
        ]),
      ),
    );
  }
}

class NewsEventMovieProjrct extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1512,
          height: 1552,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFE4E4E4)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 1401,
                child: Container(
                  width: 1512,
                  height: 151,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1512,
                          height: 151,
                          decoration: BoxDecoration(color: Color(0xFF1D1D1F)),
                        ),
                      ),
                      Positioned(
                        left: 525,
                        top: 64,
                        child: Text(
                          'Copyright © 2023 Your Title. All rights reserved.',
                          style: TextStyle(
                            color: Color(0xFFD9D9D9),
                            fontSize: 20,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1016,
                top: 865,
                child: Container(
                  width: 304,
                  height: 448,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 1,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 448,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1,
                        top: 270,
                        child: Container(
                          width: 302,
                          height: 178,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 56,
                        top: 300,
                        child: Text(
                          '‘Gran Turismo’ Ending Explained \nIf You’re Not First, You’re Last',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF1685F0),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 343,
                        child: Text(
                          'After the resounding success of HBO'
                          's The Last of Us starring \nPedro Pascal and Bella Ramsey and Tom Holland and Mark \nWahlberg'
                          's Uncharted movie in 2022, PlayStation Productions has\nbrought another of its iconic gaming franchises to live-action with \nGran Turismo. However, since the driving simulator doesn'
                          't have a \nstory mode to adapt,the movie dramatizes the real-life journey of \nJann Mardenborough, ',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 1,
                        child: Container(
                          width: 304,
                          height: 269,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/image 5.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20),
                                topRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 605,
                top: 865,
                child: Container(
                  width: 302,
                  height: 448,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 448,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 270,
                        child: Container(
                          width: 302,
                          height: 178,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 32,
                        top: 299,
                        child: Text(
                          'Star Trek: Lower Decks Is Looking To Up \nIts Body Count In Season 4',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF1685F0),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 351,
                        child: Text(
                          'For many years, death in "Star Trek" was a permanent event. To cite \na notable example: when Captain Kirks brother Sam (William Shatner) \nwas killed in the episode "Operation -- Annihilate!", he was dead \nforever. There wasn'
                          't a storyline later in the series wherein Sam was \ncloned or resurrected somehow.',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 270,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/image 4.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20),
                                topRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 193,
                top: 865,
                child: Container(
                  width: 302,
                  height: 448,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 448,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 270,
                        child: Container(
                          width: 302,
                          height: 178,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 291,
                        child: Text(
                          'How Is '
                          'Castlevania: Nocturne'
                          ' \nConnected to the Rest of the Franchise?',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF1685F0),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 341,
                        child: Text(
                          'Another fictional vampire aims to destroy the world, and just in time\nfor Halloween. This coming Thursday, Netflix will be returning to the\nworld of its critically and commercially acclaimed Castlevania series \nfor the first time since 2021 with the spin-off Castlevania: Nocturne. \nThe original Castlevania was a gem, one of the rare video game \nadaptations that beat the odds and offered a quality story on its \nown merit.',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 270,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/image 3.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20),
                                topRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1017,
                top: 328,
                child: Container(
                  width: 302,
                  height: 448,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 448,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 270,
                        child: Container(
                          width: 302,
                          height: 178,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 270,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/image 2.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20),
                                topRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 290,
                        child: Text(
                          'Tom Sandoval Is Back Hanging Out with \nScheana Shay and Trashing Rachel Leviss',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF1685F0),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 23,
                        top: 338,
                        child: Text(
                          'Tom Sandoval continues to be a mess and is proudly sharing that. \nSandoval is currently at the music festival Life Is Beautiful, which is \ninfamous in Vanderpump Rules history because it is where he and\n Rachel Leviss were together when he began cheating on his ex, \nAriana Madix. Despite his indiscretions, Sandoval refuses to \nrecognize that he plays the victim, but Scheana Shay continues to\n come to his rescue.',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 605,
                top: 328,
                child: Container(
                  width: 302,
                  height: 448,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 448,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 270,
                        child: Container(
                          width: 302,
                          height: 178,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 52,
                        top: 290,
                        child: Text(
                          'The Most Satanic Film of All Time \nPreys on Our Deepest Fears',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF1685F0),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 338,
                        child: Text(
                          'While it’s hard to pin down a singular “golden period” in the history \nof Hollywood cinema, the 1970s were certainly responsible for many \nof the classic horror films often cited as being influential today. \nThe rise of the “New Hollywood” era allowed a younger generation \nof filmmakers, international auteurs, and maverick independent \ndirectors reach a widespread audience of moviegoers thanks to the \nincreased quality of productions and the development of the \n“midnight movie” scene;',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 270,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/image 1.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20),
                                topRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 193,
                top: 328,
                child: Container(
                  width: 302,
                  height: 448,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 448,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 270,
                        child: Container(
                          width: 302,
                          height: 178,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(20),
                                bottomRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 302,
                          height: 270,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/actor-david 1.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(20),
                                topRight: Radius.circular(20),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 46,
                        top: 290,
                        child: Text(
                          'Actor David McCallum dies aged 90',
                          style: TextStyle(
                            color: Color(0xFF1685F0),
                            fontSize: 12,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 27,
                        top: 318,
                        child: Text(
                          'Glasgow-born McCallum moved to America in 1961 and was best \nknown recently for NCIS.',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 351,
                        child: Text(
                          'David McCallum, the veteran Scottish-born actor best known for \nTV hits The Man From U.N.C.L.E. and NCIS, has died aged 90.',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 384,
                        child: Text(
                          'According to a statement from CBS, the broadcast network that\n airs NCIS in the US, McCallum died of natural causes surrounded \nby family at New York Presbyterian Hospital.',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 8,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 108,
                top: 158,
                child: Container(
                  width: 1296,
                  height: 101.86,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 6,
                        child: Text(
                          'News & Events',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 25,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1254,
                        top: 0,
                        child: Container(
                          width: 42,
                          height: 42,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/42x42"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1512,
                  height: 103,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1512,
                          height: 103,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 118,
                        top: 32,
                        child: Text(
                          'Movie Rec x BFS ',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 32,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 641,
                        top: 39,
                        child: TextButton(
                          child: Text(
                            'Home',
                            style: TextStyle(
                              color: Color(0xFF1D1D1F),
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                          onPressed: () {
                            Navigator.pushReplacement(context,
                                MaterialPageRoute(builder: (context) {
                              //เปลี่ยนเป็นเว็บด้านใน
                              return FigmaToCodeApp1();
                            }));
                          },
                        ),
                      ),
                      Positioned(
                        left: 759,
                        top: 39,
                        child: TextButton(
                          child: Text(
                            'Discovery',
                            style: TextStyle(
                              color: Color(0xFF1D1D1F),
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                          onPressed: () {
                            Navigator.push(context,
                                MaterialPageRoute(builder: (context) {
                              //เปลี่ยนเป็นเว็บด้านใน
                              return MyHomePage2();
                            }));
                          },
                        ),
                      ),
                      Positioned(
                        left: 1118,
                        top: 39,
                        child: TextButton(
                          child: Text(
                            'Contaxt',
                            style: TextStyle(
                              color: Color(0xFF1D1D1F),
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                          onPressed: () {
                            Navigator.pushReplacement(context,
                                MaterialPageRoute(builder: (context) {
                              //เปลี่ยนเป็นเว็บด้านใน
                              return FigmaToCodeApp4();
                            }));
                          },
                        ),
                      ),
                      Positioned(
                        left: 915,
                        top: 39,
                        child: TextButton(
                          child: Text(
                            'New&Events',
                            style: TextStyle(
                              color: Color(0xFF1D1D1F),
                              fontSize: 20,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                          onPressed: () {
                            Navigator.pushReplacement(context,
                                MaterialPageRoute(builder: (context) {
                              //เปลี่ยนเป็นเว็บด้านใน
                              return FigmaToCodeApp3();
                            }));
                          },
                        ),
                      ),
                      Positioned(
                        left: 1239,
                        top: 32,
                        child: Container(
                          width: 239,
                          height: 39,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF5F5F7),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(50),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1310,
                        top: 41,
                        child: Container(
                          width: 20,
                          height: 20,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/20x20"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1342,
                        top: 41,
                        child: Text(
                          'Search',
                          style: TextStyle(
                            color: Color(0xFF1D1D1F),
                            fontSize: 17,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 101,
                        top: -4,
                        child: Container(
                          width: 195,
                          height: 110,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                  "pic/image/MOVIE_MINE2 1.jpg"), // ระบุ path ที่ถูกต้อง
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
